### ISSUE TITLE
Failed test with all latest components at version 2.x

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-view#53] opened 2016-03-17 15:36 UTC
https://github.com/zendframework/zend-navigation/issues/23

This seems "more" a zend-view bug when used with zend-eventmanager 2.6.3

**Comment by weierophinney** [comment] 2016-03-17 16:18
I've just tested locally by performing:

```console
$ composer update --prefer-lowest --prefer-stable
```

and then executing:

```console
$ composer require "zendframework/zend-eventmanager:^2.6.3"
```

and finally running the unit tests. The errors do not occur as reported.

I'll try also running tests in a similar fashion against zend-navigation, but in the meantime, closing here, as cannot reproduce.

**Closed by weierophinney** 2016-03-17 16:18 UTC
